apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    namespace: final
spec:
  serviceAccountName: clo835
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: paswrd
