apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
    url1: "https://si-team-final-project.s3.amazonaws.com/failed.png"
    url2: "https://si-team-final-project.s3.amazonaws.com/success.jpg"
    Group: group5