name: Deploy app image to aws ECR

on:
  push:
    branches:
      - staging
    paths:
      - webapp/*  
  workflow_dispatch:
  
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
          AWS_REGION: us-east-1
          
      - name: Seting up IMAGE_TAG variable
        id: version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    
      - name: Build, Test, Tag and push cats image to Amazon ECR
        env: 
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          ECR_REPOSITORY: clo835
          IMAGE_TAG: v1-${{ steps.version.outputs.VERSION }}
          

        run: |
          cd webapp
          ls -ltra
          # Build the docker image 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Run the container to test
          docker run -d -p 81:81 --name flask $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          # list all the containers
          docker ps
          echo " sleep 10 seconds for container to run"
          sleep 10
          # Push the docker image to ECR repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
